### ISSUE TITLE
Perfectly normal should not imply T1

### ISSUE THREAD

**Issue by kaba2** [pi-base/viewer#43]
Currently the deduction engine has a rule for perfectly normal implying T4. Via some other deductions pi-base then deduces T1. However, in general perfectly normal (as defined in Wikipedia and in Pi-base) does not imply T1 or T2. The reason is that without the T1 axiom it is not known whether singletons are closed. It would be nice if the T1 and perfectly normal properties were independent.

**Comment by jamesdabbs** [comment]
Thanks for the report! Unfortunately, it fell through the cracks and I'm just now seeing it.

We just launched a new version of the viewer at https://topology.pi-base.org, and it looks like we incidentally fixed this bug in the process. [Here](https://topology.pi-base.org/spaces?q=normal%20%2B%20~%24T_1%24) are a number of spaces that are normal but not T1 / T4. 

If you happen to check out the new viewer and notice any other issues, please let us know. (We've got better notifications set up now.)
