### ISSUE TITLE
References not showing in web pages

### ISSUE THREAD

**Issue by prabau** [pi-base/viewer#72]
Hi.  Did anything happen recently to the way the references are displayed?

As of a few days ago, the references don't show anything at all in the web pages.  See for example in
https://topology.jdabbs.com/properties/P000004/references

**Comment by StevenClontz** [comment]
This is closed in #71

**Comment by prabau** [comment]
> 
> 
> This is closed in #71

Maybe, but it's still not working at all.  Is this page working for you?
https://topology.jdabbs.com/properties/P000004/references

**Comment by StevenClontz** [comment]
No but it works in
https://topology-development.pi-base.org/properties/P000004/references so
it'll be fixed when that goes live.


Steven Clontz
https://clontz.org - steven.clontz@gmail.com

**Comment by prabau** [comment]
Thanks!
